### Добавление рецепта 1
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "name": "Сырники из творога",
  "time": 30,
  "ingredients": [
    {
      "name": "Творог",
      "count": 350,
      "measureUnit": "г."
    },
    {
      "name": "Куриное яйцо",
      "count": 2,
      "measureUnit": "шт."
    },
    {
      "name": "Пшеничная мука",
      "count": 6,
      "measureUnit": "ст.л."
    },
    {
      "name": "Сахар",
      "count": 2,
      "measureUnit": "ст.л."
    }
  ],
  "guide": [
    "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте.",
    "Всыпьте в творог муку и тщательно перемешайте.",
    "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.",
    "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду.",
    "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния.",
    "Повторяйте, пока творог не закончится."
  ]
}

### Добавление рецепта 2
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "name": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом",
  "time": 7,
  "ingredients": [
    {
      "name": "Специи",
      "count": 0,
      "measureUnit": "по вкусу"
    },
    {
      "name": "Консервированная фасоль",
      "count": 400,
      "measureUnit": "г."
    },
    {
      "name": "Лимон",
      "count": 1,
      "measureUnit": "шт."
    },
    {
      "name": "Чеснок",
      "count": 2,
      "measureUnit": "зуб."
    },
    {
      "name": "Оливковое масло",
      "count": 50,
      "measureUnit": "мл."
    },
    {
      "name": "Рукола",
      "count": 100,
      "measureUnit": "г."
    },
    {
      "name": "Творожный сыр",
      "count": 200,
      "measureUnit": "г."
    },
    {
      "name": "Красный лук",
      "count": 50,
      "measureUnit": "г."
    },
    {
      "name": "Сахар",
      "count": 2,
      "measureUnit": "ст.л."
    }
  ],
  "guide": [
    "Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой.",
    "Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром.",
    "Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."
  ]
}


### Получение рецепта по id
GET http://localhost:8080/recipes/3

### Обновление рецепта по id
PUT http://localhost:8080/recipes/1
Content-Type: application/json

{
  "name": "Чечевичный суп с мятой",
  "time": 30,
  "ingredients": [
    {
      "name": "Красная чечевица",
      "count": 150,
      "measureUnit": "г."
    },
    {
      "name": "Репчатый лук",
      "count": 1,
      "measureUnit": "шт."
    },
    {
      "name": "Морковь",
      "count": 1,
      "measureUnit": "шт."
    },
    {
      "name": "Подсолнечное масло",
      "count": 30,
      "measureUnit": "мл."
    },
    {
      "name": "Сливочное масло",
      "count": 15,
      "measureUnit": "г."
    },
    {
      "name": "Пшеничная мука",
      "count": 30,
      "measureUnit": "г."
    },
    {
      "name": "Сливки 33%",
      "count": 50,
      "measureUnit": "мл."
    },
    {
      "name": "Специи",
      "count": 0,
      "measureUnit": "по вкусу."
    },
    {
      "name": "Лимон",
      "count": 0.5,
      "measureUnit": "шт."
    },
    {
      "name": "Мята",
      "count": 0,
      "measureUnit": "по вкусу."
    }
  ],
  "guide": [
    "В небольшую кастрюлю налить литр воды и засыпать промытую чечевицу. Поставить кастрюлю на средний огонь.",
    "Натереть небольшую морковь на крупной терке, мелко нарезать лук. Как только чечевица начнет кипеть, надо убавить огонь, а затем долить еще 200 мл воды или бульона. Варить еще десять минут.",
    "Разогреть широкую плоскую сковороду, добавить туда подсолнечное и сливочное масло. Обжарить лук и морковь.",
    "Добавить обжаренные овощи в кастрюлю, влить сливки. Взбить суп ручным блендером, чтобы он превратился в густое пюре. Суп можно подавать к столу."
  ]
}

### Удаление рецепта по id
DELETE http://localhost:8080/recipes/1

### Добавление ингредиента 1
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name": "Творог",
  "count": 350,
  "measureUnit": "г."
}

### Добавление ингредиента 2
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name": "Специи",
  "count": 0,
  "measureUnit": "по вкусу"
}

### Добавление ингредиента 3
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name": "Красный лук",
  "count": 50,
  "measureUnit": "г."
}

### Добавление ингредиента 4
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name": "Сахар",
  "count": 2,
  "measureUnit": "ст.л."
}

### Добавление ингредиента 5
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "name": "Мята",
  "count": 0,
  "measureUnit": "по вкусу."
}

### Получение ингредиента по id
GET http://localhost:8080/ingredients/4

### Обновление ингредиента по id
PUT http://localhost:8080/ingredients/5
Content-Type: application/json

{
  "name": "Королевские креветки",
  "count": 300,
  "measureUnit": "г."
}

### Удаление ингредиента по id
DELETE http://localhost:8080/ingredients/1

### Получение рецептов, содержащих ингредиент с id
GET http://localhost:8080/recipes/contain/2

###  Поиск рецептов по нескольким ингредиентам
POST http://localhost:8080/recipes/contain
Content-Type: application/json

[
  {
    "name": "Куриное яйцо",
    "count": 2,
    "measureUnit": "шт."
  },
  {
    "name": "Пшеничная мука",
    "count": 6,
    "measureUnit": "ст.л."
  },
  {
    "name": "Сахар",
    "count": 2,
    "measureUnit": "ст.л."
  }
]

### Постраничный вывод рецептов
GET http://localhost:8080/recipes/all?page=1

